version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse_config:/etc/clickhouse-server/config.d
      - ./configs/clickhouse-users.xml:/etc/clickhouse-server/users.d/custom_users.xml
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=pass
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --user=default --password=pass --query='SELECT 1' && wget --spider -q http://localhost:8123/ping"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      app_net:
        aliases:
          - clickhouse-server
    # Force IPv4 only
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1

  collector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watchdata-collector
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - "4317:4317"  # OTLP gRPC
    volumes:
      - ./configs/otel-collector-config.yaml:/otel-collector-config.yaml
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=pass
      # Force IPv4 resolution
      - GODEBUG=netdns=go
    networks:
      - app_net
    # Force IPv4 only
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    # Debug connectivity before starting
    entrypoint: 
      - "sh"
      - "-c"
      - |
        echo "=== Testing ClickHouse connectivity ==="
        until nc -z clickhouse 9000; do
          echo "Waiting for ClickHouse native port..."
          sleep 2
        done
        echo "ClickHouse port 9000 is ready!"
        
        # Test ClickHouse authentication (install clickhouse-client first)
        echo "Installing ClickHouse client..."
        apt-get update && apt-get install -y clickhouse-client || echo "Failed to install clickhouse-client"
        
        echo "Testing ClickHouse authentication..."
        timeout 10s clickhouse-client --host clickhouse --port 9000 --user default --password pass --query "SELECT 1" || echo "Auth test failed - continuing anyway"
        
        echo "=== Starting collector ==="
        exec /dist/watchdataexporter --config /otel-collector-config.yaml
    restart: unless-stopped

networks:
  app_net:
    driver: bridge
    enable_ipv6: false
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  clickhouse-data: