# builder-config.yaml

build: # Builder Configuration
  platforms:
    - linux/amd64

dist:
  name: watchdata-collector
  description: "Custom Collector with watchdata exporter"
  output_path: ./dist # Where the binary will be created

otelcol:
  version: latest

components:
  receivers:
    - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v1.32.0 
      name: otlp
  exporters:
    - gomod: github.com/Ricky004/watchdata/internals/otelexporter v0.1.0
      name: watchdata
  

