# builder-config.yaml

dist:
  name: watchdataexporter
  description: "Custom Collector with watchdata exporter"
  output_path: ./dist


receivers:
  - gomod: 
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.127.0
  
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.127.0

exporters:
  - gomod: 
      github.com/Ricky004/watchdata v0.0.7-0.20250608151112-e0100499b0fc
    import: 
      github.com/Ricky004/watchdata/pkg/watchdataexporter

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.127.0