# builder-config.yaml

dist:
  name: watchdataexporter
  description: "Custom Collector with watchdata exporter"
  output_path: ./dist


receivers:
  - gomod: 
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.126.0

exporters:
  - gomod: 
      github.com/Ricky004/watchdata/pkg/watchdataexporter v0.0.1