# builder-config.yaml

dist:
  name: watchdataexporter
  description: "Custom Collector with watchdata exporter"
  output_path: ./dist


receivers:
  - gomod: 
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.126.0
  
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.126.0

exporters:
  - gomod: 
      github.com/Ricky004/watchdata v0.0.1
    import: 
      github.com/Ricky004/watchdata/pkg/watchdataexporter

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.126.0