# builder-config.yaml

build:
  platforms:
    - linux/amd64

dist:
  name: watchdata-collector
  description: "Custom Collector with watchdata exporter"
  output_path: ./dist

otelcol:
  version: latest

components:
  receivers:
    - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver latest
      name: otlp
  exporters:
     - gomod: github.com/Ricky004/watchdata/pkg/watchdataexporter latest
       name: watchdataexporter