receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4319  

exporters:
  watchdataexporter:
    endpoint: 0.0.0.0:14317  # Your backend OTLP HTTP endpoint
    api_key: ""

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [watchdataexporter]
