receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  watchdataexporter:
    endpoint: 0.0.0.0:14317  # Your backend OTLP HTTP endpoint
    insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [watchdataexporter]
