receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  filelog:
    include: [ ../tmp/test.json ]
    start_at: beginning
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%d %H:%M:%S'

processors:
  batch:

exporters:
  watchdataexporter:
    endpoint: host.docker.internal:14317  # Your backend OTLP HTTP endpoint
    insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp, filelog]
      processors: [batch]
      exporters: [watchdataexporter]
