receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4319  

exporters:
  otlphttp:
    endpoint: "http://host.docker.internal:4320"  # Your backend OTLP HTTP endpoint
    tls:
      insecure: true  # Use false if your backend supports TLS

  debug:

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug, otlphttp]
