receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4319  # client send their logs in this port

exporters:
  watchdataexporter:
    endpoint: "http://host.docker.internal:4320"  # Your backend OTLP HTTP endpoint
    api_key: 

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [watchdataexporter]
